### ISSUE TITLE
Alert

### ISSUE THREAD

**Issue by loveorigami** [rokorolov/parus#1]
Привет.
В свое время я тоже думал, как выводить флеш сообщения. 

Можешь посмотреть мой модуль 
https://github.com/loveorigami/yii2-notification-wrapper

чтобы избавиться от 
https://github.com/rokorolov/parus/search?utf8=%E2%9C%93&q=alert

+ при случае - можно легко сменить библиотеку показа флешей (для разный тем или разрешений экрана), не завязываясь на js-скриптах

**Comment by rokorolov** [comment]
Интересное решение и то что можно будет избавится от AjaxAlertTrait тоже как бы подталкивает.
Единственное что пока останавливает это то что надо тянуть целый модуль с не малым функционалом который мне пока не требуется. Так как сейчас для отображения сообщений используется виджет в несколько строк.

Думаю дополнить виджет вашим решением и если вдруг понадобится дополнительный функционал тогда уже подтянуть ваш модуль. 

> при случае - можно легко сменить библиотеку показа флешей (для разный тем или разрешений экрана), не завязываясь на js-скриптах 

Использую http://bootstrap-notify.remabledesigns.com так что разрешение экрана не проблема.

**Comment by loveorigami** [comment]
Из как-бы "ненужного", что представляет модуль - это классы-обертки под выбранную библиотеку.

https://github.com/loveorigami/yii2-notification-wrapper/tree/master/src/layers
Они занимают всего то ничего, по сравнению с самим Yii ))), например
https://github.com/loveorigami/yii2-notification-wrapper/blob/master/src/layers/Growl.php

Все остальное - надо.

Спасибо за ссылку
http://bootstrap-notify.remabledesigns.com 

Добавлю и для этой библтиотеки реализацию.
