### ISSUE TITLE
Error in menu logic

### ISSUE THREAD

**Issue by markxxv** [rokorolov/parus#3]
I found little bug in menu logic, when I adding some page in menu (select from list) it have's slug page/**show**?id=1 but isn't work because correct url is  page/**view**?id=1

**Comment by rokorolov** [comment]
Update module with composer (still dev), clear cache and try again.

**Comment by markxxv** [comment]
Yes, now rout is a correct, but slug isn't working. When I add for example page About in menu, now appears the correct route `page/view?id=1` but on click the menu now appears 404. But previously when i changed page/**show?**id=1 to page/**view?**id=1 was worked slug about.

**Comment by rokorolov** [comment]
If the error appears only with slug 'about' then the problem is in web config, exactly in urlManager configuration, try remove 'about' from rule '<action:(about|contact|gallery)>' => 'page/<action>'

**Comment by markxxv** [comment]
Exactly. Now its work perfect. Thank you.
